services:

  postgres:
    image: postgres:16
    container_name: leadzen_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: leadzen
      POSTGRES_USER: leadzen
      POSTGRES_PASSWORD: leadzenpass
      EMAIL_USER: leadzendemo@gmail.com
      EMAIL_PASS: wkbs sgic nimx tvrk
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: leadzen_redis
    restart: unless-stopped

  api:
    build: .
    container_name: leadzen_api
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"

  worker:
    build: .
    container_name: leadzen_worker
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: celery -A app.celery_app.celery worker --loglevel=info

volumes:
  postgres_data: